// <auto-generated />
using System;
using IsoBridge.Infrastructure.Audit;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IsoBridge.Infrastructure.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    [Migration("20251108225418_InitAudit")]
    partial class InitAudit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.36");

            modelBuilder.Entity("IsoBridge.Core.Audit.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HmacSignature")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrevHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestDigest")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseDigest")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("AuditEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
